name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js environment 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: SolidJS Build
        run: pnpm -dir apps/solid run build

      - name: SolidJS Test
        if: success() || failure()
        run: pnpm -dir apps/solid run test

      - name: SolidJS Typeckeck
        if: success() || failure()
        run: pnpm -dir apps/solid run typecheck

      - name: SolidJS Lint
        if: success() || failure()
        run: pnpm -dir apps/solid run lint
